### ISSUE TITLE
error: could not find the release corresponding to tag v1.3

### ISSUE THREAD

**Issue by QingYanL** [github-release/github-release#107]
github-release v0.8.1

- run 
```
export GITHUB_TOKEN=XXXXX
export HASH=$(git rev-parse HEAD)
export BRANCH=$(basename $(git branch -r --contains ${HASH}))
export tag=$(basename $(git describe --all --exact-match ${HASH}))

echo "HASH: $HASH"
echo "BRANCH: $BRANCH"
echo "TAG: $tag"
VERSION=${tag//v/}
echo "VERSION: $VERSION"

true||./github-release release \
  --user QingYanL  \
  --repo mavendemo  \
  --tag ${tag} \
  --name ${tag}  \
  --relaese

./github-release upload  \
  --user QingYanL \
  --repo mavendemo \
  --tag ${tag} \
  --name cita_sm2_sm3-${VERSION}.tar.gz \
  --file ./cita_sm2_sm3.tar.gz -R
```

error: could not find the release corresponding to tag v1.3
![image](https://user-images.githubusercontent.com/48231505/84107768-1df6ae00-aa51-11ea-9821-1f487d4032fa.png)

I confirm the existence tag for v1.3
(https://github.com/QingYanL/mavendemo/releases/tag/v1.3)

Please help me. What should I do ?

**Comment by QingYanL** [comment]
I try update .tar.gz to .zip 
error: Get "https://api.github.com/repos/QingYanL/mavendemo/releases?per_page=100": dial tcp 13.250.168.23:443: connect: connection refused

![image](https://user-images.githubusercontent.com/48231505/84112051-a0d03680-aa5a-11ea-8683-8e9efa0c1473.png)


If I want to upload .tar.gz , what I can do

**Comment by kevinburke** [comment]
I think this is an issue with the Github UI. It shows Git tags on the "releases" page, but you need to explicitly click on 'Draft a release' and associate it with the tag.

Try running:

```
github-release release --tag v1.3 ...
```

before you run:

```
github-release upload ...
```
