### ISSUE TITLE
go get is picking up v0.8.1 not v0.9.0

### ISSUE THREAD

**Issue by ncw** [github-release/github-release#109]
I'm not sure why this is but `go get` is getting an old version of github-release

Here is a demo with a clean go install

```
$ cd /tmp/
$ mkdir go
$ ls go
$ export GOPATH=/tmp/go
$ go get github.com/github-release/github-release
$ /tmp/go/bin/github-release --version
github-release v0.8.1
```

```
$ go version
go version go1.15.2 linux/amd64
```

**Comment by kevinburkemeter** [comment]
this should be fixed now, apologies, can you try it out? latest version should be 0.10.0.

**Comment by ncw** [comment]
That is working fine now :-) Thank you!
