### ISSUE TITLE
.env support? 

### ISSUE THREAD

**Issue by retorquere** [github-release/github-release#74]
Does github-release have .env support? If not, could it be added?

**Comment by aktau** [comment]
What is `.env` support, if I may ask?

It doesn't support it now, I think (depending on what it is).

**Comment by retorquere** [comment]
Sorry: https://github.com/joho/godotenv

It picks up environment variables from a special file in the current directory, so you can vary vars per invocation / project.

**Comment by hartzell** [comment]
You can use [direnv](https://direnv.net/) (also written in go!) to handle this without changing github-release.

**Comment by kevinburke** [comment]
Hi, this is not a priority but you're welcome to use direnv or envdir from daemontools to implement on your own! Best of luck.
