### ISSUE TITLE
Can't install on my server 

### ISSUE THREAD

**Issue by majenkotech** [github-release/github-release#79]
```
$ go get github.com/aktau/github-release
# github.com/aktau/github-release
go/src/github.com/aktau/github-release/cmd.go:96: enc.SetIndent undefined (type *json.Encoder has no field or method SetIndent)
```
go version go1.6 linux/amd64

**Comment by kun-zhou** [comment]
some issue here

**Comment by antmak** [comment]
Try to use static build https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2

It works everywhere

**Comment by tsauvajon** [comment]
How do you uncompress this file ?
```
curl -s $GITHUB_RELEASE | tar xvjf -
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

**Comment by kevinburke** [comment]
Going to mark this as resolved, please reopen if you run into further problems.

**Comment by majenkotech** [comment]
I obviously fixed it somehow. I have no clue what I did, but suffice it to say I had completely forgotten about the issue...
