### ISSUE TITLE
Failed upload leaks credentials

### ISSUE THREAD

**Issue by bndw** [github-release/github-release#85]
First, thanks for providing a simple tool for working with Github releases!

It appears that when using the `upload` command to a non-existent repository, the `access_token` is leaked in the error message. This is a problem when running this tool in an open-source project's CI system.

```
bin/linux/amd64/github-release
error: expected '200 OK' but received '404 Not Found' (url: https://api.github.com/repos/envoy-bot/envoy/releases?access_token=MY_ACCESS_TOKEN&per_page=100)
```

**Comment by jc21** [comment]
In addition to this, the access token should not be in the URL as it is deprecated. Github sent me a message about this today.

Since the project looks dead, looks like I'll be using one of the forks and if they don't fix this, I'll be forking the fork..

**Comment by alertedsnake** [comment]
> In addition to this, the access token should not be in the URL as it is deprecated. Github sent me a message about this today.
> 
> Since the project looks dead, looks like I'll be using one of the forks and if they don't fix this, I'll be forking the fork..

@jc21 did you fork the fork?  I need this fix as well :)

**Comment by kevinburkemeter** [comment]
I thought I fixed this... is it not fixed?

**Comment by ocdtrekkie** [comment]
It's worth noting the official gh tool supports release management now, depending on your situation, switching to the official tool may be a good option now.

**Comment by alertedsnake** [comment]
@ocdtrekkie I just noticed that myself!  So disregard my comments here, I'll use their tool instead.

**Comment by kevinburkemeter** [comment]
apologies for the delay; I've just merged the fix
