### ISSUE TITLE
error: could not upload, status code (504 Gateway Time-out)

### ISSUE THREAD

**Issue by ko-ichi-h** [github-release/github-release#87]
Thank you very much for developing this nice software and providing us binaries! It really helps.

I can upload small binary files without errors.  But when I try to upload a larger file (550MB), I got this error.  Here is the last part --verbose message.

> setting content-length to 586121216
> RESPONSE: &{504 Gateway Time-out 504 HTTP/1.1 1 1 map[Content-Type:[text/html] Content-Length:[176] X-Github-Request-Id:[A96B:9647:6704B7:6C263B:5AFDB043] Server:[GitHub.com] Date:[Thu, 17 May 2018 16:41:23 GMT]] 0xc0420e6b80 176 [] false false map[] 0xc042240100 0xc0422722c0}
> error: could not upload, status code (504 Gateway Time-out)

My upload speed is about 100 Mbps. I am using "windows-amd64-github-release.zip" on Windows 10 64bit.

Strangely, though I see the above error on my command prompt window, the file seems to be uploaded without problem. I could download the file and the file was OK.

Any possible solutions?

Thank you.

**Comment by kevinburke** [comment]
My guess is the Github API just had a hiccup. I would suggest trying the request again if this happens or building in retry logic.
