### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by SteelPhase** [github-release/github-release#95]
It appears that the maintainer is not responding to Pull Requests, or issues, and there hasn't been any changes since 2017

**Comment by kuboosoft** [comment]
Maybe the developer doesn't have time... fork it and merge the pull requests... I am using github-release is a great piece of software... @aktau

**Comment by antmak** [comment]
I use https://github.com/itchio/gothub - a little changed fork with more convenient name

**Comment by ocdtrekkie** [comment]
Question: Does this offer any functionality `hub release` doesn't? https://github.com/github/hub

It looks like Hub added release functionality in 2018, which might explain why the developer stopped bothering after 2017.

**Comment by antmak** [comment]
@ocdtrekkie 
> Does this offer any functionality hub release doesn't?

`hub` is very awkward . It requires a clone of some GH repo to update a few assets in a release of some project.

**Comment by aktau** [comment]
It was dead for a very long time, but @kevinburke (AKA @kevinburkemeter) has agreed to take over maintainership. He had already been maintaining a fork (https://github.com/meterup/github-release).

> hub is very awkward . It requires a clone of some GH repo to update a few assets in a release of some project.

Perhaps it would also be a good idea to tell the hub(1) developers that this is not ideal. IMHO it's always better to use a CLI tool maintained by the people implementing the API.
